name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Inject Firebase config
      run: |
        # Create a temporary file with the Firebase configuration
        cat > firebase-config.js << EOL
        // Firebase Configuration - Injected during build
        const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
        };
        EOL
    
    - name: Update index.html
      run: |
        # Add the firebase-config.js script to index.html
        sed -i '/<script src="https:\/\/www.gstatic.com\/firebasejs\/9.6.10\/firebase-storage-compat.js"><\/script>/a \    <script src="firebase-config.js"></script>' index.html
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .  # Deploy the entire repository
        branch: gh-pages
