name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Inject Firebase config directly into HTML
      run: |
        sed -i '/<script src="app.js"><\/script>/i \    <script>\n        // Firebase Configuration - Injected during build\n        const firebaseConfig = {\n            apiKey: "${{ secrets.FIREBASE_API_KEY }}",\n            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",\n            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",\n            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",\n            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",\n            appId: "${{ secrets.FIREBASE_APP_ID }}",\n            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"\n        };\n    </script>' index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
